### ISSUE TITLE
When a game should end with a draw, player 1 wins

### ISSUE THREAD

**Issue by tiramon** [CodinGame/game-ultimate-tictactoe#3]
In the following replays Player 1 wins even if both games should end in a draw ...

https://www.codingame.com/replay/294828703
https://www.codingame.com/replay/294828741

Line causing this problem is propably the endgame without setwinner here
https://github.com/CodinGame/game-ultimate-tictactoe/blob/master/src/main/java/com/codingame/game/Referee.java#L246-L249

in theory this should result in both players having 0 score ... so it still looks like a draw

Is there maybe a bug in the codingame-sdk?

**Comment by MaximeCheramy** [comment]
I need to update the statement to precise that at the end of the game, to avoid a draw, the winner is the player that won the most small boards.

**Comment by tiramon** [comment]
and if both won the same amount of small boards? Then it is handled as normal draw?

And yes i found it in L237 you get a score for every small grid won

**Comment by MaximeCheramy** [comment]
That's a draw.

**Comment by MaximeCheramy** [comment]
Statement updated
